### PR TITLE
Added SSL Cert Verification option

### PR DESCRIPTION
**Pull request by mo-cmyk**
Added the option to use a custom SSL Certificate when using proxies. This fix passes a custom verify option to the python requests default verify parameter.
Otherwise, the package would have thrown an SSL Error when using proxies since the python requests module wasn't able to verify the SSL Certs and therefore  authenticate the HTTPS Requests

@tgherzog Would be great if you could take a look at it.

### CODE REVIEW

**Review by tgherzog — COMMENTED** [review]
The trouble is that setting verify=False in this manner raises warnings in urllib, which seems to really prefer that SSL certificates be enabled. I think this raises more issues that it solves. If SSL certificates are failing then the problem lies either in the API server or elsewhere in the user's installation.

**Comment by mo-cmyk** [comment]
Yes, but otherwise, proxy use is not possible, and the only way to use the API on a large scale would be a Monkey Patch enabling the feature you just denied, which seems like an unnecessary hustle. Why offer the proxy feature anyway, then?

**Comment by tgherzog** [comment]
Okay, you convinced me ;) but I implemented a more general approach which allows you to change all parameters to `requests.get` to allow more flexibility. Update to version 1.0.10 please.

**Comment by mo-cmyk** [comment]
> Okay, you convinced me ;) but I implemented a more general approach which allows you to change all parameters to `requests.get` to allow more flexibility. Update to version 1.0.10 please.

Sounds like a good idea. Thanks!

**Pull request closed without merging**
